#!/usr/bin/env python
"""
annotate_pdf.py - Insert interactive link annotations into PDF

Reads the index.json file generated by extract_tags.py and creates a new PDF
with clickable link annotations that jump between tag occurrences.

Usage:
    python annotate_pdf.py <input_pdf> <output_pdf> [--index <index_file>]

Example:
    python annotate_pdf.py "2024_05_24 90_ CD Set.pdf" "annotated_output.pdf"
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

try:
    import fitz  # PyMuPDF
except ImportError:
    print("Error: PyMuPDF (fitz) not installed. Run: pip install PyMuPDF")
    sys.exit(1)


def load_index(index_path: Path) -> Dict[str, Any]:
    """
    Load the tag index from JSON file.
    
    Args:
        index_path: Path to index.json
        
    Returns:
        Tag index dictionary
    """
    if not index_path.exists():
        raise FileNotFoundError(f"Index file not found: {index_path}")
    
    with open(index_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def create_annotated_pdf(input_pdf: str, output_pdf: str, index: Dict[str, Any]) -> None:
    """
    Create a new PDF with link annotations based on the tag index.
    
    Args:
        input_pdf: Path to input PDF file
        output_pdf: Path to output PDF file
        index: Tag index data
    """
    input_path = Path(input_pdf)
    if not input_path.exists():
        raise FileNotFoundError(f"Input PDF not found: {input_path}")
    
    doc = fitz.open(input_path)
    
    print(f"Adding annotations to '{input_path.name}'...")
    print(f"Processing {len(index['tags'])} tags...")
    
    annotation_count = 0
    
    # Iterate through each tag and its occurrences
    for tag, occurrences in index['tags'].items():
        if len(occurrences) < 2:
            # Skip tags with only one occurrence (no backlinks to create)
            continue
        
        # For each occurrence, create links to all other occurrences
        for i, occurrence in enumerate(occurrences):
            page_num = occurrence['page'] - 1  # Convert to 0-indexed
            bbox = occurrence['bbox']
            
            page = doc[page_num]
            rect = fitz.Rect(bbox['x0'], bbox['y0'], bbox['x1'], bbox['y1'])
            
            # Create a link annotation that goes to the next occurrence (circular)
            next_idx = (i + 1) % len(occurrences)
            next_occurrence = occurrences[next_idx]
            target_page = next_occurrence['page'] - 1
            
            # Add link annotation
            link = {
                'kind': fitz.LINK_GOTO,
                'from': rect,
                'page': target_page,
                'to': fitz.Point(
                    next_occurrence['bbox']['x0'],
                    next_occurrence['bbox']['y0']
                )
            }
            
            page.insert_link(link)
            annotation_count += 1
            
            # Add a highlight annotation to make it visible
            highlight = page.add_highlight_annot(rect)
            highlight.set_colors(stroke=(0, 0.5, 1))  # Blue highlight
            highlight.set_opacity(0.3)
            highlight.update()
    
    # Save the annotated PDF
    output_path = Path(output_pdf)
    doc.save(output_path, garbage=4, deflate=True)
    doc.close()
    
    print(f"Annotations added: {annotation_count}")
    print(f"Annotated PDF saved to: {output_path.absolute()}")


def main():
    parser = argparse.ArgumentParser(
        description='Insert interactive link annotations into PDF based on tag index'
    )
    parser.add_argument(
        'input_pdf',
        help='Path to the input PDF file'
    )
    parser.add_argument(
        'output_pdf',
        help='Path to the output PDF file'
    )
    parser.add_argument(
        '--index', '-i',
        default='index.json',
        help='Path to index.json file (default: index.json)'
    )
    
    args = parser.parse_args()
    
    try:
        # Load the tag index
        print(f"Loading index from: {args.index}")
        index = load_index(Path(args.index))
        
        # Create annotated PDF
        create_annotated_pdf(args.input_pdf, args.output_pdf, index)
        
        print("\nAnnotation complete!")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
